application: wa2-helpdesk
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /docs
  static_dir: docs

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: main.py
